### ISSUE TITLE
[question] Multiple CSProj files - some locked some not. how to score?

### ISSUE THREAD

**Issue by balteravishay** [balteravishay/scorecard#8]
Looking at a repo such as [this](https://github.com/Mongo2Go/Mongo2Go) where there are three csproj files, one of them is leveraging the RestoreLockedMode feature, what do we expect?

* A relative score (i.e. 1/3 nuget dependencies are pinned)
* A zero score (i.e. unpinned dependencies found in the repo)
* A positive score (i.e. dependencies are pinned)
* Any other thought?

**Comment by balteravishay** [comment]
Update in daily: Current implementation is to have a relative score (1/3 nuget dependencies are pinned)

**Comment by JonDouglas** [comment]
"pinned dependencies" generally refer to specifying exact versions of dependencies in your project's configuration files (e.g., package.json, requirements.txt, csproj, etc.)

the 1/3 projects having a lock file I think might be an ADDITIONAL check ontop of that requirement.

thus my knowledge here, this project would be 3/3 given each .csproj has a pinned dependency.

we may need to improve detection if we only check lock files. lock files can be used separately to pinned versions and would account for the same "check" if my knowledge is correct here.

**Comment by aortiz-msft** [comment]
If it were me, I would use an all or nothing approach. Supply chain security is as good as the weakest link.
